// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductServiceApi.Data;

namespace ProductServiceApi.Data.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20250114114741_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProductServiceApi.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A powerful laptop",
                            Name = "Laptop",
                            Price = 999.99m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 2,
                            Description = "A high-end smartphone",
                            Name = "Smartphone",
                            Price = 499.99m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 3,
                            Description = "A lightweight tablet",
                            Name = "Tablet",
                            Price = 299.99m,
                            Quantity = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
